### Site Settings ###
title               : KRDesigns.com
description         : >-
                      creativity + coffee,
                      work + play = done
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : krdesigns-com/krdesigns-com.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : krdesigns-com/krdesigns-com.github.io


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
#  - documentation/partials/**                           # For Documentation Only


### Author Info ###
author:
  name              : Richard Tirtadji
  image             : /img/profile.jpg
# behance           : your_username
# dribbble          : your_username
  email             : rtirtadji@gmail.com
  facebook          : richard.tirtadji
  github            : ranrinc
# gitlab            : your_username
  instagram         : ranrinc
  linkedin          : richard-tirtadji
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : richardtirtadji
# vimeo             : your_username
# youtube           : your_channel_name


### Posts ###
permalink: /articles/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements:                                             # For Documentation Only
    output: true                                        # For Documentation Only


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
#  - scope:                                              # For Documentation Only
#      path: ""                                          # For Documentation Only
#      type: "elements"                                  # For Documentation Only
#    values:                                             # For Documentation Only
#      layout: "element"                                 # For Documentation Only


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"

# Analytics
prod-analytics-id: UA-159820849-1